### ISSUE TITLE
官方的rtmp示例无法正常播放

### ISSUE THREAD

**Issue by simmzl** [surmon-china/videojs-player#125]
该项目的[官方rtmp示例](https://surmon-china.github.io/vue-video-player/) 出现了无法播放的问题，不知道是什么原因？
在我测试rtmp视频时本地开发可以播放，但build上线后无法播放，console报错：`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.`不知道官方示例无法播放是不是同样的问题。
测试了Issues:[使用hls的时候在本地是正常的，编译放在服务器上就不显示了](https://github.com/surmon-china/vue-video-player/issues/90)下提到的方法均不生效。

**Comment by simmzl** [comment]
"video.js": "^6.4.0",
    "vue-video-player": "^4.0.6",
    "videojs-flash": "^2.0.1",

**Comment by surmon-china** [comment]
版本问题，最新版组件 v5.0.0 将解决此问题。

**Comment by surmon-china** [comment]
已发布，记得删除 `node_modules` 重新安装。

**Comment by simmzl** [comment]
@surmon-china 官方RTMP示例还是不能播放

**Comment by surmon-china** [comment]
我这里没问题啊，一直都没问题啊，是不是你网络的问题，自己找在线的 rtmp 源用来测试。

**Comment by shen-lan** [comment]
依然不行

**Comment by qq854674282** [comment]
我的也不可以，求大牛指教

**Comment by indextg** [comment]
我的也不行，放服务器上报The "flash" tech is undefined. Skipped browser support check for that tech

**Comment by surmon-china** [comment]
videojs 最新版里，flash 默认是不被支持的，需要单独安装 videojs-flash 包来支持，各位试试

**Comment by surmon-china** [comment]
#185

**Comment by indextg** [comment]
我的解决了，我更换了node的版本就好了，之前是9，换成10以后就好了

**Comment by qq854674282** [comment]
我解决的方案是使用video标签，虽然很low，但是满足需求，抱歉，我弃坑了

**Comment by shen-lan** [comment]
着

> 我解决的方案是使用video标签，虽然很low，但是满足需求，抱歉，我弃坑了

`http://chimee.org/`
强烈推荐试下这个。除了不支持`flash` 
其他的都ok

**Comment by qq854674282** [comment]
谢谢同学，我试下

**Comment by qq854674282** [comment]
> 谢谢同学，我试下



> 着
> 
> > 我解决的方案是使用video标签，虽然很low，但是满足需求，抱歉，我弃坑了
> 
> `http://chimee.org/`
> 强烈推荐试下这个。除了不支持`flash`
> 其他的都ok



> 着
> 
> > 我解决的方案是使用video标签，虽然很low，但是满足需求，抱歉，我弃坑了
> 
> `http://chimee.org/`
> 强烈推荐试下这个。除了不支持`flash`
> 其他的都ok

谢谢同学，我试下

**Comment by StephenOo** [comment]
rtmp依然不可以，官方有解决方案么

**Comment by HydrogenPan19** [comment]
原因应该是，video-flash 和 vue-video-player 获取的 video.js 不是同一个，导致后者拿不到 flash tech

**Comment by nongzhenli** [comment]
没有解决，依然不行~

**Comment by FrontendStack** [comment]
![image](https://user-images.githubusercontent.com/58390198/87615558-9255f880-c745-11ea-83e9-4f72a508ee43.png)
rtmp 官方示例都没法播放,估计是无解 了

**Comment by surmon-china** [comment]
rtmp 已不再被支持，若有直播需求，可参照新版 example 配置 HLS/DASH/FLV。
