### ISSUE TITLE
rtmp

### ISSUE THREAD

**Issue by krystal-bin** [surmon-china/videojs-player#147]
没有是否开启flash的询问

**Comment by surmon-china** [comment]
也许和浏览器设置有关，很多浏览器新版已经默认禁用了

**Comment by clement10601** [comment]
Try something like this
works on chrome & firefox
```
require('videojs-flash')

export default {
    data () {
      playerOptions: {
        sources: [{
          type: "rtmp/mp4",
          withCredentials: false,
          src: ""
        }],
        techOrder: ['flash'],
        width: 480,
        height: 480,
        autoplay: true,
        controls: true,
        live: true,
        flash: {
          swf: 'http://' + location.hostname + '/video-js.swf'
        }
      }
    }
}
```

**Comment by yzfgithub** [comment]
本地环境跑起来完全没问题，但是在线上就报这个错误：

**Comment by yzfgithub** [comment]
VIDEOJS: ERROR: The "flash" tech is undefined. Skipped browser support check for that tech.
K @ video.cjs.js:450
W.error @ video.cjs.js:572
(anonymous) @ video.cjs.js:22072
t.selectSource @ video.cjs.js:22062
t.src_ @ video.cjs.js:22219
(anonymous) @ video.cjs.js:22176
e @ video.cjs.js:9361
e @ video.cjs.js:9363
(anonymous) @ video.cjs.js:9189
i @ video.cjs.js:2285
(anonymous) @ video.cjs.js:4488
setTimeout (async)
e.setTimeout @ video.cjs.js:4486
vn @ video.cjs.js:9188
t.src @ video.cjs.js:22168
play @ klass.vue:556
(anonymous) @ show.vue:48
success @ network_util.js:4
(anonymous) @ fetcher.js:115
Promise.then (async)
wr @ fetcher.js:114
load @ show.vue:37
created @ show.vue:54
wt @ vue.esm.js:2921
e._init @ vue.esm.js:4630
s @ vue.esm.js:4798
(anonymous) @ vue.esm.js:4310
init @ vue.esm.js:4131
(anonymous) @ vue.esm.js:5608
d @ vue.esm.js:5555
m @ vue.esm.js:5682
d @ vue.esm.js:5584
(anonymous) @ vue.esm.js:6091
e._update @ vue.esm.js:2660
(anonymous) @ vue.esm.js:2788
Pt.get @ vue.esm.js:3142
Pt @ vue.esm.js:3131
(anonymous) @ vue.esm.js:2795
hn.$mount @ vue.esm.js:8540
hn.$mount @ vue.esm.js:10939
init @ vue.esm.js:4137
(anonymous) @ vue.esm.js:5608
d @ vue.esm.js:5555
m @ vue.esm.js:5682
d @ vue.esm.js:5584
(anonymous) @ vue.esm.js:6091
e._update @ vue.esm.js:2660
(anonymous) @ vue.esm.js:2788
Pt.get @ vue.esm.js:3142
Pt @ vue.esm.js:3131
(anonymous) @ vue.esm.js:2795
hn.$mount @ vue.esm.js:8540
hn.$mount @ vue.esm.js:10939
init @ vue.esm.js:4137
(anonymous) @ vue.esm.js:5608
d @ vue.esm.js:5555
m @ vue.esm.js:5682
d @ vue.esm.js:5584
(anonymous) @ vue.esm.js:6091
e._update @ vue.esm.js:2660
(anonymous) @ vue.esm.js:2788
Pt.get @ vue.esm.js:3142
Pt @ vue.esm.js:3131
(anonymous) @ vue.esm.js:2795
hn.$mount @ vue.esm.js:8540
hn.$mount @ vue.esm.js:10939
init @ vue.esm.js:4137
(anonymous) @ vue.esm.js:5608
d @ vue.esm.js:5555
m @ vue.esm.js:5682
d @ vue.esm.js:5584
(anonymous) @ vue.esm.js:6091
e._update @ vue.esm.js:2660
(anonymous) @ vue.esm.js:2788
Pt.get @ vue.esm.js:3142
Pt @ vue.esm.js:3131
(anonymous) @ vue.esm.js:2795
hn.$mount @ vue.esm.js:8540
hn.$mount @ vue.esm.js:10939
init @ vue.esm.js:4137
(anonymous) @ vue.esm.js:5608
d @ vue.esm.js:5555
(anonymous) @ vue.esm.js:6130
e._update @ vue.esm.js:2660
(anonymous) @ vue.esm.js:2788
Pt.get @ vue.esm.js:3142
Pt @ vue.esm.js:3131
(anonymous) @ vue.esm.js:2795
hn.$mount @ vue.esm.js:8540
hn.$mount @ vue.esm.js:10939
e._init @ vue.esm.js:4640
hn @ vue.esm.js:4729
NHnr @ main.js:29
t @ bootstrap 26db66812ae4f9bdb3bb:54
window.webpackJsonp @ bootstrap 26db66812ae4f9bdb3bb:25
(anonymous) @ app.bd9860a5093c52d3e6fe.js:1
video.cjs.js:450 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. Lt {code: 4, message: "No compatible source was found for this media."}

**Comment by yzfgithub** [comment]
本地跑没问题，但是推到线上
报错：
![image](https://user-images.githubusercontent.com/20821815/45879633-ce350680-bdd7-11e8-8da9-4acef143cd35.png)

**Comment by shen-lan** [comment]
> 本地跑没问题，但是推到线上
> 报错：
> ![image](https://user-images.githubusercontent.com/20821815/45879633-ce350680-bdd7-11e8-8da9-4acef143cd35.png)
大兄弟解决了吗 一模一样的问题

**Comment by labnize** [comment]
`playerOptions: {
autoplay: false, // 如果true,浏览器准备好时开始回放。
muted: false, // 默认情况下将会消除任何音频。
loop: false, // 导致视频一结束就重新开始。
preload: 'auto', // 建议浏览器在加载元素后是否应该开始下载视频数据。auto浏览器选择最佳行为,立即开始加载视频（如果浏览器支持）
language: 'zh-CN',
aspectRatio: '4:3', // 将播放器置于流畅模式，并在计算播放器的动态大小时使用该值。值应该代表一个比例 - 用冒号分隔的两个数字（例如"16:9"或"4:3"）
fluid: true, // 当true时，Video.js player将拥有流体大小。换句话说，它将按比例缩放以适应其容器。
techOrder: ['flash', 'html5'],
flash: { hls: { withCredentials: false } },
html5: { hls: { withCredentials: false } },
sources: [{
type: 'rtmp/mp4',
// src: 'rtmp://36.248.23.130:50005/live/streamname', // 你的m3u8地址（必填
src: 'rtmp://v.kitebeam.com/live/9846_8d8efcdb64f59f43a095' // 你的m3u8地址（必填
}],
poster: '/img/ces.png', // 你的封面地址
notSupportedMessage: '此视频暂无法播放，请稍后再试', // 允许覆盖Video.js无法播放媒体源时显示的默认信息。
controlBar: {
timeDivider: true,
durationDisplay: true,
remainingTimeDisplay: false,
fullscreenToggle: true // 全屏按钮
}
}`

安装完vue-video-player后，需要单独安装videojs-flash。
**我用yarn安装后，一直也报这两个错。**
**后来发现是版本不匹配的问题，进行了版本降级。目前vue-video-player使用的是@5.0.1，videojs-flash使用的是@2.1.0。不报错了。

用npm安装，也不会出现报错。**

**Comment by labnize** [comment]
playerOptions: {
autoplay: false, // 如果true,浏览器准备好时开始回放。
muted: false, // 默认情况下将会消除任何音频。
loop: false, // 导致视频一结束就重新开始。
preload: 'auto', // 建议浏览器在加载元素后是否应该开始下载视频数据。auto浏览器选择最佳行为,立即开始加载视频（如果浏览器支持）
language: 'zh-CN',
aspectRatio: '4:3', // 将播放器置于流畅模式，并在计算播放器的动态大小时使用该值。值应该代表一个比例 - 用冒号分隔的两个数字（例如"16:9"或"4:3"）
fluid: true, // 当true时，Video.js player将拥有流体大小。换句话说，它将按比例缩放以适应其容器。
techOrder: ['flash', 'html5'],
flash: { hls: { withCredentials: false } },
html5: { hls: { withCredentials: false } },
sources: [{
type: 'rtmp/mp4',
// src: 'rtmp://36.248.23.130:50005/live/streamname', // 你的m3u8地址（必填
src: 'rtmp://v.kitebeam.com/live/9846_8d8efcdb64f59f43a095' // 你的m3u8地址（必填
}],
poster: '/img/ces.png', // 你的封面地址
notSupportedMessage: '此视频暂无法播放，请稍后再试', // 允许覆盖Video.js无法播放媒体源时显示的默认信息。
controlBar: {
timeDivider: true,
durationDisplay: true,
remainingTimeDisplay: false,
fullscreenToggle: true // 全屏按钮
}
}

**安装完vue-video-player后，需要单独安装videojs-flash。**
**我用yarn安装后，一直也报这两个错。**
**后来发现是版本不匹配的问题，进行了版本降级。目前vue-video-player使用的是@5.0.1，videojs-flash使用的是@2.1.0。不报错了。**
**用npm安装，也不会出现报错。**
