### ISSUE TITLE
我想问下在用vue打包时候video.js 本地模拟没事线上跑没事可是在ipad 8.1版本就会出现没有进度条以及部分按钮，我需要怎么做能解决这类问题

### ISSUE THREAD

**Issue by huanghanzhilian** [surmon-china/videojs-player#149]
我想问下在用vue打包时候video.js 本地模拟没事线上跑没事可是在ipad 8.1版本就会出现没有进度条以及部分按钮，我需要怎么做能解决这类问题

**Comment by surmon-china** [comment]
The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
