### ISSUE TITLE
v-for循环一个列表的播放视频

### ISSUE THREAD

**Issue by wanghuai123** [surmon-china/videojs-player#165]
现在业务是有一个列表的视频数据，需要做循环处理 怎么给src赋值呢

**Comment by yanqi321** [comment]
<video-player class="vjs-custom-skin" ref="videoPlayer" :options="getOptions(item.content.video_url)" :playsinline="true">
            </video-player>
我是通过option 给他传src的

**Comment by lhwtyu** [comment]
将传递的参数写成一个方法可以解决： 
playerOptions(item, index) {
      const options = {
        playbackRates: [0.7, 1.0, 1.5, 2.0], // 播放速度
        autoplay: false, // 如果true,浏览器准备好时开始回放。
        muted: false, // 默认情况下将会消除任何音频。
        loop: false, // 导致视频一结束就重新开始。
        preload: 'auto', // 建议浏览器在<video>加载元素后是否应该开始下载视频数据。auto浏览器选择最佳行为,立即开始加载视频（如果浏览器支持）
        language: 'zh-CN',
        aspectRatio: '16:9', // 将播放器置于流畅模式，并在计算播放器的动态大小时使用该值。值应该代表一个比例 - 用冒号分隔的两个数字（例如"16:9"或"4:3"）
        fluid: true, // 当true时，Video.js player将拥有流体大小。换句话说，它将按比例缩放以适应其容器。
        poster: item.videoImg, //你的封面地址
        notSupportedMessage: '此视频暂无法播放，请稍后再试', // 允许覆盖Video.js无法播放媒体源时显示的默认信息。
        timeDivider: true,
        durationDisplay: true,
        remainingTimeDisplay: false,
        fullscreenToggle: false // 全屏按钮
      }
      return Object.assign(options, {
        sources: [
          {
            type: 'video/mp4',
            src: item.video.src
          }
        ]
      })
    },

**Comment by Sjling** [comment]
在nuxt中,v-for只出来第一个数据,后面的出不来了........

**Comment by truthiswong** [comment]
请问这个具体是怎么循环出来的?

**Comment by shaohui-wang** [comment]
> 在nuxt中，v-for只出来第一个数据，后面的出不来了........

遇到了同样的问题，没找到解决办法

**Comment by shaohui-wang** [comment]
https://github.com/surmon-china/vue-video-player/issues/52#issuecomment-294504895
