### ISSUE TITLE
 this.el_.vjs_getProperty is not a function弹窗关闭时，一直报错

### ISSUE THREAD

**Issue by zhangdoudou** [surmon-china/videojs-player#244]
1. 弹窗关闭时，一直报错
2.当前版本为^5.0.2
3. video.cjs.js?0e26:440 VIDEOJS: ERROR: TypeError: this.el_.vjs_getProperty is not a function
    at Flash.currentTime (videojs-flash.js?e2e1:543)
    at get$1 (video.cjs.js?0e26:9281)
    at Player.techGet_ (video.cjs.js?0e26:21528)
    at Player.currentTime (video.cjs.js?0e26:21737)
    at SeekBar.getCurrentTime_ (video.cjs.js?0e26:12608)
    at SeekBar.getPercent (video.cjs.js?0e26:12635)
    at SeekBar.update (video.cjs.js?0e26:11932)
    at SeekBar.update (video.cjs.js?0e26:12590)
    at bound (video.cjs.js?0e26:2344)
    at SeekBar.throttled (video.cjs.js?0e26:2377)
看之前的issues，说是在3.0版本fix这个问题，但是现在出现了，麻烦大家告知一下如何解决谢谢

**Comment by zhangdoudou** [comment]
"videojs-flash": "^2.1.2",
"vue-video-player": "^5.0.2"

**Comment by SXZXD** [comment]
跟你遇到了一样得错误，关闭模态，player没有销毁，就报这个错

**Comment by SXZXD** [comment]
解决方法：模态关闭是调用销毁：videoPlayer.dispose()，模态打开时初始化：videoPlayer.initialize()

**Comment by zhangdoudou** [comment]
@SXZXD 太感谢了，解决了我的燃眉之急

**Comment by SXZXD** [comment]
不客气！

**Comment by lwjxj** [comment]
我也遇到了这个问题，能贴下具体代码吗？非常感谢！

**Comment by lwjxj** [comment]
@SXZXD

**Comment by SXZXD** [comment]
> 我也遇到了这个问题，能贴下具体代码吗？非常感谢！

![image](https://user-images.githubusercontent.com/31951973/92579416-bf470780-f2bf-11ea-968e-57bac78c86b0.png)

监听你model框的变化，分别调用元组件的方法就好了

**Comment by lwjxj** [comment]
我这边没有弹窗，是切换大屏幕。都是复用的这个组件




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SXZXD"<notifications@github.com&gt;; 
发送时间: 2020年9月9日(星期三) 下午5:16
收件人: "surmon-china/vue-video-player"<vue-video-player@noreply.github.com&gt;; 
抄送: "刘伟"<1097408921@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [surmon-china/vue-video-player]  this.el_.vjs_getProperty is not a function弹窗关闭时，一直报错 (#244)





  
我也遇到了这个问题，能贴下具体代码吗？非常感谢！
  

 
监听你model框的变化，分别调用元组件的方法就好了

**Comment by SXZXD** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    切换大屏幕？如果你切换的操作，会引起组件的显示隐藏，那么就得按照这样的逻辑处理
    
    
    

    

    

    在2020年09月9日 17:23，lwjxj<notifications@github.com> 写道： 




我这边没有弹窗，是切换大屏幕。都是复用的这个组件



















------------------&nbsp;原始邮件&nbsp;------------------



发件人: "SXZXD"<notifications@github.com&gt;; 



发送时间: 2020年9月9日(星期三) 下午5:16



收件人: "surmon-china/vue-video-player"<vue-video-player@noreply.github.com&gt;; 



抄送: "刘伟"<1097408921@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 



主题: Re: [surmon-china/vue-video-player]  this.el_.vjs_getProperty is not a function弹窗关闭时，一直报错 (#244)























  



我也遇到了这个问题，能贴下具体代码吗？非常感谢！



  







 



监听你model框的变化，分别调用元组件的方法就好了

**Comment by lwjxj** [comment]
为什么需要这样写，不是很明白，还请指教。当我从lcd切换到led的时候就报错了







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "surmon-china/vue-video-player"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 下午5:37
收件人:&nbsp;"surmon-china/vue-video-player"<vue-video-player@noreply.github.com&gt;;
抄送:&nbsp;"刘伟"<1097408921@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [surmon-china/vue-video-player]  this.el_.vjs_getProperty is not a function弹窗关闭时，一直报错 (#244)





 
 
      
 
 
 
     font{ 
         line-height: 1.6; 
     } 
     ul,ol{ 
         padding-left: 20px; 
         list-style-position: inside; 
     } 
 
 
     
     切换大屏幕？如果你切换的操作，会引起组件的显示隐藏，那么就得按照这样的逻辑处理
     
     
     
 
     
 
     
 
     在2020年09月9日 17:23，lwjxj<notifications@github.com&gt; 写道： 
 
 
 
 
 我这边没有弹窗，是切换大屏幕。都是复用的这个组件
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 
 
 
 发件人: "SXZXD"<notifications@github.com&amp;gt;; 
 
 
 
 发送时间: 2020年9月9日(星期三) 下午5:16
 
 
 
 收件人: "surmon-china/vue-video-player"<vue-video-player@noreply.github.com&amp;gt;; 
 
 
 
 抄送: "刘伟"<1097408921@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;; 
 
 
 
 主题: Re: [surmon-china/vue-video-player]  this.el_.vjs_getProperty is not a function弹窗关闭时，一直报错 (#244)
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
   
 
 
 
 我也遇到了这个问题，能贴下具体代码吗？非常感谢！
 
 
 
   
 
 
 
 
 
 
 
  
 
 
 
 监听你model框的变化，分别调用元组件的方法就好了

**Comment by yangbing007** [comment]
解决了我的问题！！！感谢！！！🥳

**Comment by surmon-china** [comment]
The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
