### ISSUE TITLE
video.js7.4.1了，接受PR吗

### ISSUE THREAD

**Issue by IEfucker** [surmon-china/videojs-player#250]
当前使用的是^6.6.0
m3u8等格式不支持，项目有更新计划吗，或者PR接受吗

**Comment by QuincyC379** [comment]
> 当前使用的是^6.6.0
> m3u8等格式不支持，项目有更新计划吗，或者PR接受吗

这哥们一年没更了，估计退休转行了！

**Comment by hefeng1208** [comment]
>当前使用的是^6.6.0
m3u8等格式不支持，项目有更新计划吗，或者PR接受吗

>这哥们一年没更了，估计退休转行了！

正解啊

**Comment by surmon-china** [comment]
更，年后，我没退休，只是有个人的事耽误了

**Comment by otary** [comment]
还没更新版本吗？

**Comment by surmon-china** [comment]
Done
