### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by JeremeLau** [surmon-china/videojs-player#252]
I have a request: play 3 local videos loop
when I changed src frequently， memory leaks

here's my code
`playerOptions: {
          autoplay: true,
          muted: false,
          language: 'en',
          controls: false,
          sources: [{
            type: "video/mp4",
            // mp4
            //src: "http://vjs.zencdn.net/v/oceans.mp4",
            src: "static/videos/0.mp4"
            // webm
            // src: "https://cdn.theguardian.tv/webM/2015/07/20/150716YesMen_synd_768k_vp8.webm"
          }],
          aspectRatio: '16:9',
          notSupportedMessage: '此视频暂无法播放，请稍后再试',
          poster: "https://surmon-china.github.io/vue-quill-editor/static/images/surmon-1.jpg",
        },`

`selectVideo(index) {
        this.selectIndex = index
        this.playerOptions.sources = [{
          type: "video/mp4",
          src: 'static/videos/' + index + '.mp4'
        }]
        //this.playerOptions.sources[0].src = 'static/videos/' + index + '.mp4'
      }`

**Comment by 15915940450** [comment]
i meet the same problem,some body help?

**Comment by surmon-china** [comment]
The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
