### ISSUE TITLE
VIDEOJS: ERROR: The "flash" tech is undefined. Skipped browser support check for that tech

### ISSUE THREAD

**Issue by SXZXD** [surmon-china/videojs-player#253]
Unable to play flv video
"vue-video-player": "^5.0.2"
"videojs-flash": "2.1.2"
 This question has been mentioned many times and still exists

**Comment by dest86** [comment]
try 
    "vue-video-player": "5.0.2",
    "video.js": "6.13.0",
    "videojs-contrib-hls": "5.15.0",
    "videojs-flash": "2.1.2",
    "videojs-hotkeys": "0.2.22",
    "videojs-swf": "5.4.2"

**Comment by surmon-china** [comment]
The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
