### ISSUE TITLE
playeroptions sources

### ISSUE THREAD

**Issue by pocketChao** [surmon-china/videojs-player#261]
### 中文用户注意：

Can I set headers for sources
The video server needs to be encrypted and I need to pass in a parameter

![issue](https://user-images.githubusercontent.com/21028807/54671859-c1e4f880-4b31-11e9-8db5-e73866f19270.jpg)

**Comment by surmon-china** [comment]
The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
