### ISSUE TITLE
拖动进度条时的回调问题。

### ISSUE THREAD

**Issue by NickBang** [surmon-china/videojs-player#303]
修改视频时间的时候是否有回调？api中并没有找到。现需要做两个视频同步播放的需求，修改时间暂无法解决。

**Comment by surmon-china** [comment]
API: [`currentTime(secondsopt)`](https://docs.videojs.com/player#currentTime)

The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
