### ISSUE TITLE
视频列表内暂停无效

### ISSUE THREAD

**Issue by lishuliang28** [surmon-china/videojs-player#307]
在el-table中，把video-player 放在el-popover使用，通过el-popover的显示和隐藏控制video的播放和暂停。
问题描述
1、问题在show中播放视频，和展示的视频不一直。
2、如果通过预览打开视频，在hide时候，视频仍在播放没有停止。
代码如下：
 <el-table-column
            label="视频预览">
            <template slot-scope="scope">
              <el-popover
                placement="top"
                width="640"
                trigger="click"
                @show="popShowBefore(scope.row.userId)"
                @hide="popHideAfter(scope.row.userId)"
                >
                <div>
                <video-player  class="video-player vjs-custom-skin"
                               :ref="'videoPlayer'+ scope.row.userId"
                               :playsinline="true"
                               :options="playerOptions"
                ></video-player>
                </div>
                <el-button slot="reference" >click 激活</el-button>
              </el-popover>
            </template>
          </el-table-column>

**Comment by lishuliang28** [comment]
<el-popover
                placement="top"
                width="640"
                trigger="click"
                @show="popShowBefore(scope.row.userId)"
                @hide="popHideAfter(scope.row.userId)"
                >
                <div>
                <video-player  class="video-player vjs-custom-skin"
                               :ref="'videoPlayer'+ scope.row.userId"
                               :playsinline="true"
                               :options="playerOptions"
                ></video-player>
                </div>
                <el-button slot="reference" >click 激活</el-button>
              </el-popover>

**Comment by surmon-china** [comment]
业务问题需要通过业务逻辑解决。

1. 通过控制 popover 弹出层来控制组件的生命周期（mount & unmount）
2. 手动调用 videojs 实例来控制播放与视频切换
