### ISSUE TITLE
pc播放器播放m3u8的时候，我需要设置请求头，上传token，做验证。怎么设置不了，改源码一设置就报错

### ISSUE THREAD

**Issue by YangCccong** [surmon-china/videojs-player#310]
![image](https://user-images.githubusercontent.com/46803227/62411339-f1e5f180-b623-11e9-86e5-a73a8209c1a8.png)
headers["accept"] || headers["Accept"] || (headers["Accept"] = "application/json, text/plain, */*") //Don't override existing accept header declared by user
        headers['Authorization'] = options.json.Authorization
for(key in headers){
          console.log(key)
          console.log(headers[key])
          console.log(headers.hasOwnProperty(key))
          if(headers.hasOwnProperty(key)){
            xhr.setRequestHeader(key, headers[key])
          }
 }
下面的值也传过来了，设置不成功。

**Comment by Luoyayu** [comment]
using xhook to inject xhr request

**Comment by surmon-china** [comment]
The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.

**Comment by theores** [comment]
> 原包不再维护，请升级到。`vue-video-player``@videojs-player/vue`

请问下，该如何设置请求头？
