### ISSUE TITLE
Cannot be used in weex projects

### ISSUE THREAD

**Issue by goolorn** [surmon-china/videojs-player#313]
vue.runtime.esm.js?12a6:619 [Vue warn]: Error in mounted hook: "TypeError: this.$refs.video.setAttribute is not a function"

vue.runtime.esm.js?12a6:619[Vue warn]: Error in mounted hook: "TypeError: The element or ID supplied is not valid. (videojs)"

help!thanks

**Comment by surmon-china** [comment]
The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
