### ISSUE TITLE
vue porject --Video.js causes memory leaks【videojs导致了内存泄漏（移动端vue项目）】

### ISSUE THREAD

**Issue by Lxshmily** [surmon-china/videojs-player#317]
This is useful if you are having trouble with This plugin resetting itself to loading when you have introduced video.js in my vue project, which caused memory leakage. Has anyone solved This problem?
【在我的vue 项目中，引入的video.js导致了内存泄漏，请问有人解决过这方面的问题吗？】

**Comment by yangkunwei** [comment]
video.js@7.5.5版本已经解决内存泄漏问题，但是该插件还引用@6.0版本，只要手动升级下video.js即可，也建议作者将该项目升级下video.js的版本 @surmon-china

**Comment by surmon-china** [comment]
The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
