### ISSUE TITLE
vue/video.js/memory leaks 

### ISSUE THREAD

**Issue by blackkillday** [surmon-china/videojs-player#318]
In my  vue project , the introduction of video-js caused the leakage of memory . Has anyone ever solved this problem？

**Comment by blackkillday** [comment]
In my  vue project , the introduction of video-js caused the leakage of memory . Has anyone ever solved this problem？

**Comment by yangkunwei** [comment]
https://github.com/surmon-china/vue-video-player/issues/317#issuecomment-533772976

**Comment by surmon-china** [comment]
The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
