### ISSUE TITLE
video.js^7.0.0 maybe not compatible with current vue-video-player

### ISSUE THREAD

**Issue by FanShiDe** [surmon-china/videojs-player#342]
Sometimes, we maybe install video.js in our project, current version of video.js is `7.6.6`, we want to override style so we require it in our code like this:

```js
require('video.js/dist/video-js.css')
```
But finally, there are some errors: 
* incorrect UI

* `CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED`

* something that has n’t happened yet

The video.js defined in `package.json` of `vue-video-player`:

https://github.com/surmon-china/vue-video-player/blob/388e09f24dae09380f5b5699b0202ebef203446c/package.json#L51

The video.js defined in `package.json` in own project:

```js
"video.js": "^7.6.6."
```

There are two `video.js` versions in our project, one is we defined, anther one is `vue-video-player` defined，you just change the version of video.js which is defined by yourself to be the same with the version in `vue-video-player`, change version in your `package.json` like this:

```js
"video.js": "^6.6.0",
or
"video.js": "6.6.0",
```

Hope to help you

**Comment by surmon-china** [comment]
The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
