### ISSUE TITLE
nuxt使用，找不到this.refs.xxx.player

### ISSUE THREAD

**Issue by xiaojinsongwusha** [surmon-china/videojs-player#370]
设置ref了但是找不到player，是还需要安装其它的依赖么

**Comment by apache820** [comment]
我也遇到这个问题了 还没解决，有什么办法吗？

**Comment by jinagko** [comment]
我也是，查了半天都没找到怎么解决～有没有人知道怎么处理nuxt 的 refs

**Comment by zhengkai7651** [comment]
我也是，但是我发现是因为在设置了 ref的节点上 加了v-if的判断 ，因为输当前vue 的this对象查看到是有ref这对象的但是具体值是undefined，所以我把v-if向节点内移动了不在ref的节点上加v-if 就可以通过ref找到节点了！

**Comment by surmon-china** [comment]
The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
