### ISSUE TITLE
vue-video-player播放时断网后出现默认英文报错信息，能否将其换成中文的，我将报错提示关闭后视频中出现播放按钮，链接网络再次点击播放按钮，视频无法播放

### ISSUE THREAD

**Issue by zongyi1996** [surmon-china/videojs-player#376]
### 中文用户注意：

1. 尽量用英文描述你的 issue
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，必须仔细阅读 REMADE.md + 在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决
5. **如果无法做到提一个合格、优秀的问题，则问题会被 close + block**

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/39epgLj0/

#### What is actually happening?

**Comment by surmon-china** [comment]
建议升级新版，Video.js 有内置的 i18n 系统，通过 `language` 和 `languages` 控制。

The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
