### ISSUE TITLE
这个播放器必须依靠flash吗?

### ISSUE THREAD

**Issue by kason888** [surmon-china/videojs-player#382]
这个播放器必须依靠flash吗?
可以不用flash播放HTTP-FLV协议吗？

**Comment by SXZXD** [comment]
不可以，flv必须依靠flash

**Comment by surmon-china** [comment]
false 已被放弃支持，如果需要播放 flv 视频，可参照新版 flv example 进行配置开发。

The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
