### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by jd-solanki** [surmon-china/videojs-player#389]
As Vue 3 has RC It will be a good idea to add support for Vue 3.

Currently, if we use this package with Vue 3 we are getting error.

![image](https://user-images.githubusercontent.com/47495003/93457005-18d0b700-f8fc-11ea-8cc9-a516e1a877ab.png)

**Comment by ddmy** [comment]
+1

**Comment by chenhaijun2019** [comment]
![image](https://user-images.githubusercontent.com/49867880/117751226-50072600-b247-11eb-9bd0-6ef79050f555.png)

**Comment by surmon-china** [comment]
Support for Vue3 has been released, so stay tuned for the latest homepage at https://github.com/surmon-china/videojs-player.
