### ISSUE TITLE
Cannot read property 'play' of undefined Cannot read property 'U' of undefined  安装了 无数次 看了无数教程就没一个能用的

### ISSUE THREAD

**Issue by yewenkang** [surmon-china/videojs-player#395]
### 中文用户注意：

1. 尽量用英文描述你的 issue
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，必须仔细阅读 REMADE.md + 在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决
5. **如果无法做到提一个合格、优秀的问题，则问题会被 close + block**

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/39epgLj0/

#### What is actually happening?

**Comment by xiaoForest** [comment]
我vue3里用的这个，提示报错 
Uncaught (in promise) TypeError: Cannot read property '_c' of undefined
o(╥﹏╥)o

**Comment by q774221810** [comment]
@xiaoForest 解决了么

**Comment by xiaoForest** [comment]
> @xiaoForest 解决了么

没有，最后用的阿里云播放器，改了下UI，先凑合用着

**Comment by LiuTodd** [comment]
> 我vue3里用的这个，提示报错
> Uncaught (in promise) TypeError: Cannot read property '_c' of undefined
> o(╥﹏╥)o

同样问题

**Comment by xiaoForest** [comment]
> > 我vue3里用的这个，提示报错
> > Uncaught (in promise) TypeError: Cannot read property '_c' of undefined
> > o(╥﹏╥)o
> 
> 同样问题

dplayer 貌似还可以，还没用，

**Comment by 838239178** [comment]
> 我vue3里用的这个，提示报错
> Uncaught (in promise) TypeError: Cannot read property '_c' of undefined
> o(╥﹏╥)o
改源码可解决适配vue3的问题 我发了个pullrequest了

**Comment by surmon-china** [comment]
试一下最新版，针对 Vue3 做了诸多优化。
