### ISSUE TITLE
vue nuxt框架引入vue-video-player 版本5.0.2 引入报错 window is not defined

### ISSUE THREAD

**Issue by 1332310977** [surmon-china/videojs-player#397]
![QQ图片20201117112730](https://user-images.githubusercontent.com/41411339/99343016-0d801480-28c8-11eb-9c8c-89e8d44f24fd.png)
![QQ图片20201117112813](https://user-images.githubusercontent.com/41411339/99343021-0eb14180-28c8-11eb-8a54-cc77ad1e56c8.png)

 import VideoPlayer from 'vue-video-player';
 "vue-video-player": "^5.0.2"

感谢各位老哥 帮忙看看问题

**Comment by 9527Robin** [comment]
`
 { src: '~plugins/nuxt-video-player-plugin.js', ssr: false }
`

**Comment by surmon-china** [comment]
The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
