### ISSUE TITLE
整合flv.js问题

### ISSUE THREAD

**Issue by lihuazhang323** [surmon-china/videojs-player#398]
现在vue-video-player 无法整合flv.js 播放flv  是否能更新下 解决这个问题

**Comment by surmon-china** [comment]
建议升级新版，且可在新版本的演示站找到 [Flv example](https://github.surmon.me/videojs-player) 相关代码。

The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
