### ISSUE TITLE
支持vue3么

### ISSUE THREAD

**Issue by q774221810** [surmon-china/videojs-player#405]
支持vue3么

**Comment by ddmy** [comment]
+1

**Comment by RobenQ** [comment]
+1

**Comment by daleizi** [comment]
vue3 vite 下安装  报错 Uncaught SyntaxError: The requested module '/@modules/vue-video-player/dist/vue-video-player.js' does not provide an export named 'default'

**Comment by daleizi** [comment]
vue3 vite 下安装  报错 Uncaught SyntaxError: The requested module '/@modules/vue-video-player/dist/vue-video-player.js' does not provide an export named 'default'

**Comment by 838239178** [comment]
不支持但是我改了源码就支持了

**Comment by yuki9du** [comment]
> > 那得改好多处吧，改api的话
> 
> 看我的pullrequest就知道了
能加个微信吗，q282651244，我怕改的有遗漏

**Comment by surmon-china** [comment]
支持，来了，可以先 Beta 版尝鲜 https://github.com/surmon-china/videojs-player。
