### ISSUE TITLE
options 参数写在标签上，数据更新会强制刷新video

### ISSUE THREAD

**Issue by whl0718** [surmon-china/videojs-player#416]
`<div key="video-player">
			<video-player
				:options="{
					width: '600px',
					height: '350px',
					fluid: false,
					sources: [
						{
							src: 'https://xxxxx.mp4'
						}
					]
				}"
			></video-player>
		</div>
	<input v-model="key"/>`
options 参数写在标签上，当input数据更新时，video-player也会强制更新

`<div key="video-player">
			<video-player
				:options="options"
			></video-player>
		</div>
	<input v-model="key"/>`
如果将options用响应数据来包裹就不会出现上述问题，虽然发现问题，但不明白为什么，求指导学习

**Comment by lolPlatinumPlayer** [comment]
不止是options写在标签上有这个情况，options用method返回也会有这个情况
只要触发updated生命周期，那视频也会被刷新

**Comment by GitDjAr** [comment]
> 不止是options写在标签上有这个情况，options用method返回也会有这个情况
> 只要触发updated生命周期，那视频也会被刷新
有没有解决办法啊,好困扰,只要是同级触发updtae就会更新

**Comment by GitDjAr** [comment]
> 不止是options写在标签上有这个情况，options用method返回也会有这个情况
> 只要触发updated生命周期，那视频也会被刷新

有没有解决办法啊,好困扰,只要是同级触发updtae就会更新

**Comment by surmon-china** [comment]
设计缺陷，旧版不再维护，请使用新版。

The original `vue-video-player` package is no longer maintained, please upgrade to `@videojs-player/vue`.
