### ISSUE TITLE
无法调用暂停视频的方法

### ISSUE THREAD

**Issue by lixinliA** [surmon-china/videojs-player#441]
### Describe the bug

我在vue3+ts中使用无法调用暂停视频的方法

### Reproduction

![image](https://user-images.githubusercontent.com/20835672/185048557-cae405c1-60d1-4641-ae58-d0ac6c58f3fb.png)
![image](https://user-images.githubusercontent.com/20835672/185048584-b329d8ff-9c8b-4f6d-bab9-80d355a6a1e8.png)
![image](https://user-images.githubusercontent.com/20835672/185048646-a1da1cb2-fe33-4754-b468-a341cd06a3f2.png)

### System Info

```shell
谷歌浏览器
```

### Used Package Manager

pnpm

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by surmon-china** [comment]
可能的排查方向：`timeUpdate` 事件可能会在 `mounted` 之前执行，如果是，则此时 `videoRef` 确实为空，加个非空判断活着 `?.` 运算符即可。

**Comment by surmon-china** [comment]
另外：`PlayerState` 是一个 readonly 的响应式对象，天然基于 Vue 系统且自洽，所以如果你需要消费（衍生）一些播放器状态，应尽量使用 computed，如：

```ts
const remainingTime = computed(() => {
  return state.value
    ? state.value.duration - state.value.currentTime
    : 0
})
```

副作用可以基于数据状态的变化，而非事件，如：

```ts
watch(
  () => state.value?.currentTime,
  (time) => {
    if (time === 5) {
      // do something ...
    }
  }
)
```
